### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by mnguyen-io**
update to api 4.15.1 and api-derive 4.15.1

### CODE REVIEW

**Comment by dillu24** [comment]
Hi @mnguyen-io thanks for contributing to our project!

Would you be able to add a description in the unreleased section of the `CHANGELOG` located in the `docs` folder?

**Comment by dillu24** [comment]
Apart from my previous comment all looks ok right @DanielMagro97 ?

**Comment by mnguyen-io** [comment]
> Hi @mnguyen-io thanks for contributing to our project!
> 
> Would you be able to add a description in the unreleased section of the `CHANGELOG` located in the `docs` folder?

**Comment by mnguyen-io** [comment]
> Hi @mnguyen-io thanks for contributing to our project!
> 
> Would you be able to add a description in the unreleased section of the `CHANGELOG` located in the `docs` folder?

No problem. All done.

**Pull request closed without merging**
